<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Introducción modelos pronóstico | Universidad Javeriana Cali Maestría en Ciencia de Datos</title>
  <meta name="description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Introducción modelos pronóstico | Universidad Javeriana Cali Maestría en Ciencia de Datos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  <meta name="github-repo" content="raulfdocastro/SeriesTiempoPUJCali" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Introducción modelos pronóstico | Universidad Javeriana Cali Maestría en Ciencia de Datos" />
  
  <meta name="twitter:description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  

<meta name="author" content="Joan Sebastián García Villa" />
<meta name="author" content="Laura Yohanna Bermúdez Murillo" />
<meta name="author" content="Raúl Fernando Castro Suárez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preprocesamiento-y-visualización.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="propuesta.html"><a href="propuesta.html"><i class="fa fa-check"></i><b>1</b> Propuesta Bookdown Grupo 7</a>
<ul>
<li class="chapter" data-level="1.1" data-path="propuesta.html"><a href="propuesta.html#tipo-de-datos"><i class="fa fa-check"></i><b>1.1</b> Tipo de datos</a></li>
<li class="chapter" data-level="1.2" data-path="propuesta.html"><a href="propuesta.html#importancia-del-pronóstico"><i class="fa fa-check"></i><b>1.2</b> Importancia del pronóstico</a></li>
<li class="chapter" data-level="1.3" data-path="propuesta.html"><a href="propuesta.html#fuente-de-datos"><i class="fa fa-check"></i><b>1.3</b> Fuente de datos</a></li>
<li class="chapter" data-level="1.4" data-path="propuesta.html"><a href="propuesta.html#consideraciones-finales"><i class="fa fa-check"></i><b>1.4</b> Consideraciones finales</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> Estructura de las series de tiempo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#variables-a-analizar"><i class="fa fa-check"></i><b>2.1</b> Variables a analizar</a></li>
<li class="chapter" data-level="2.2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#conjunto-de-datos"><i class="fa fa-check"></i><b>2.2</b> Conjunto de datos</a></li>
<li class="chapter" data-level="2.3" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#series-tiempo"><i class="fa fa-check"></i><b>2.3</b> Series de tiempo</a></li>
<li class="chapter" data-level="2.4" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#datos-faltantes"><i class="fa fa-check"></i><b>2.4</b> Datos faltantes</a></li>
<li class="chapter" data-level="2.5" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#EDA"><i class="fa fa-check"></i><b>2.5</b> Análisis exploratorio</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#boxplots"><i class="fa fa-check"></i><b>2.5.1</b> Boxplots</a></li>
<li class="chapter" data-level="2.5.2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#histogramas"><i class="fa fa-check"></i><b>2.5.2</b> Histogramas</a></li>
<li class="chapter" data-level="2.5.3" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#análisis-por-años"><i class="fa fa-check"></i><b>2.5.3</b> Análisis por años</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#observaciones-finales"><i class="fa fa-check"></i><b>2.6</b> Observaciones finales</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html"><i class="fa fa-check"></i><b>3</b> Preprocesamiento y visualización</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#medias-móviles"><i class="fa fa-check"></i><b>3.1</b> Medias móviles</a></li>
<li class="chapter" data-level="3.2" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#descomposición"><i class="fa fa-check"></i><b>3.2</b> Descomposición</a></li>
<li class="chapter" data-level="3.3" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#dickey-fuller-test"><i class="fa fa-check"></i><b>3.3</b> Dickey-Fuller Test</a></li>
<li class="chapter" data-level="3.4" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#funciones-de-autocorrelación-acf-y-pacf"><i class="fa fa-check"></i><b>3.4</b> Funciones de autocorrelación (ACF y PACF)</a></li>
<li class="chapter" data-level="3.5" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#rezagos"><i class="fa fa-check"></i><b>3.5</b> Rezagos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html"><i class="fa fa-check"></i><b>4</b> Introducción modelos pronóstico</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#tendencias-y-ciclos"><i class="fa fa-check"></i><b>4.1</b> Tendencias y ciclos</a></li>
<li class="chapter" data-level="4.2" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#modelo-holt-winters"><i class="fa fa-check"></i><b>4.2</b> Modelo Holt-Winters</a></li>
<li class="chapter" data-level="4.3" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#predicciones-iniciales"><i class="fa fa-check"></i><b>4.3</b> Predicciones iniciales</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Universidad Javeriana Cali<br />
Maestría en Ciencia de Datos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introducción-modelos-pronóstico" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Capítulo 4</span> Introducción modelos pronóstico<a href="introducción-modelos-pronóstico.html#introducción-modelos-pronóstico" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En el presente capítulo se aplica la metodología Holt-Winter y de suavizamiento a las series de tiempo estudiadas en el documento. Con los <em>datasets</em> procesados en los capítulos 2 <a href="estructura-de-las-series-de-tiempo.html#conjunto-de-datos">Conjunto de datos</a> y 3 <a href="preprocesamiento-y-visualización.html#preprocesamiento-y-visualización">Preprocesamiento y visualización</a>, se procede con los análisis en mención.</p>
<div id="tendencias-y-ciclos" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Tendencias y ciclos<a href="introducción-modelos-pronóstico.html#tendencias-y-ciclos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se seleccionan las series con años seguidos con datos, por lo que se analizarán la precipitación total diaria de Bogotá entre los años 2018 y 2019 y la temperatura máxima diaria de Medellín entre 2022 y 2023.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introducción-modelos-pronóstico.html#cb94-1" tabindex="-1"></a><span class="co"># Serie xts Precipitación total diaria Bogotá 2018-2019</span></span>
<span id="cb94-2"><a href="introducción-modelos-pronóstico.html#cb94-2" tabindex="-1"></a>BOG_rain_2018_2019 <span class="ot">&lt;-</span> df_rain_ts[<span class="st">&quot;2018/2019&quot;</span>, <span class="st">&quot;BOG&quot;</span>]</span>
<span id="cb94-3"><a href="introducción-modelos-pronóstico.html#cb94-3" tabindex="-1"></a><span class="fu">str</span>(BOG_rain_2018_2019)</span></code></pre></div>
<pre><code>## An xts object on 2018-01-01 / 2019-12-31 containing: 
##   Data:    double [730, 1]
##   Columns: BOG
##   Index:   Date [730] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="introducción-modelos-pronóstico.html#cb96-1" tabindex="-1"></a><span class="fu">class</span>(BOG_rain_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="introducción-modelos-pronóstico.html#cb98-1" tabindex="-1"></a><span class="fu">start</span>(BOG_rain_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;2018-01-01&quot;</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="introducción-modelos-pronóstico.html#cb100-1" tabindex="-1"></a><span class="fu">end</span>(BOG_rain_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;2019-12-31&quot;</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="introducción-modelos-pronóstico.html#cb102-1" tabindex="-1"></a><span class="fu">frequency</span>(BOG_rain_2018_2019)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="introducción-modelos-pronóstico.html#cb104-1" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(BOG_rain_2018_2019))</span></code></pre></div>
<pre><code>## BOG 
##   0</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="introducción-modelos-pronóstico.html#cb106-1" tabindex="-1"></a><span class="co"># Serie ts Precipitación total diaria Bogotá 2018-2019</span></span>
<span id="cb106-2"><a href="introducción-modelos-pronóstico.html#cb106-2" tabindex="-1"></a>BOG_rain_2018_2019_ts <span class="ot">&lt;-</span> <span class="fu">as.ts</span>(BOG_rain_2018_2019)</span>
<span id="cb106-3"><a href="introducción-modelos-pronóstico.html#cb106-3" tabindex="-1"></a><span class="fu">class</span>(BOG_rain_2018_2019_ts)</span></code></pre></div>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="introducción-modelos-pronóstico.html#cb108-1" tabindex="-1"></a><span class="fu">str</span>(BOG_rain_2018_2019_ts)</span></code></pre></div>
<pre><code>##  Time-Series [1:730] from 1 to 730: 13.8 0.1 2.2 0 17.1 0.3 0.1 0 5.6 8.8 ...</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="introducción-modelos-pronóstico.html#cb110-1" tabindex="-1"></a><span class="fu">summary</span>(BOG_rain_2018_2019_ts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   1.683   0.975  32.400</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="introducción-modelos-pronóstico.html#cb112-1" tabindex="-1"></a><span class="co"># Serie xts Temperatura máxima diaria Medellín 2022-2023</span></span>
<span id="cb112-2"><a href="introducción-modelos-pronóstico.html#cb112-2" tabindex="-1"></a>MED_temp_2022_2023 <span class="ot">&lt;-</span> df_temp_max_ts[<span class="st">&quot;2022/2023&quot;</span>, <span class="st">&quot;MED&quot;</span>]</span>
<span id="cb112-3"><a href="introducción-modelos-pronóstico.html#cb112-3" tabindex="-1"></a><span class="fu">str</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## An xts object on 2022-01-01 / 2023-12-31 containing: 
##   Data:    double [730, 1]
##   Columns: MED
##   Index:   Date [730] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="introducción-modelos-pronóstico.html#cb114-1" tabindex="-1"></a><span class="fu">class</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="introducción-modelos-pronóstico.html#cb116-1" tabindex="-1"></a><span class="fu">start</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;2022-01-01&quot;</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="introducción-modelos-pronóstico.html#cb118-1" tabindex="-1"></a><span class="fu">end</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;2023-12-31&quot;</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="introducción-modelos-pronóstico.html#cb120-1" tabindex="-1"></a><span class="fu">frequency</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="introducción-modelos-pronóstico.html#cb122-1" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(MED_temp_2022_2023))</span></code></pre></div>
<pre><code>## MED 
##   0</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="introducción-modelos-pronóstico.html#cb124-1" tabindex="-1"></a><span class="co"># Serie ts Temperatura máxima diaria Medellín 2022-2023</span></span>
<span id="cb124-2"><a href="introducción-modelos-pronóstico.html#cb124-2" tabindex="-1"></a>MED_temp_2022_2023_ts <span class="ot">&lt;-</span> <span class="fu">as.ts</span>(MED_temp_2022_2023)</span>
<span id="cb124-3"><a href="introducción-modelos-pronóstico.html#cb124-3" tabindex="-1"></a><span class="fu">class</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="introducción-modelos-pronóstico.html#cb126-1" tabindex="-1"></a><span class="fu">str</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>##  Time-Series [1:730] from 1 to 730: 27.4 26.4 27.8 28 28.2 26 25 26.8 27.4 24.6 ...</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="introducción-modelos-pronóstico.html#cb128-1" tabindex="-1"></a><span class="fu">summary</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   20.60   26.50   28.00   27.93   29.40   32.60</code></pre>
<p>Primero graficamos con <code>plot</code> la tendencia de la serie de tiempo / xts para las variables a analizar en este apartado:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="introducción-modelos-pronóstico.html#cb130-1" tabindex="-1"></a><span class="co"># Plot xts Precipitación Bogotá</span></span>
<span id="cb130-2"><a href="introducción-modelos-pronóstico.html#cb130-2" tabindex="-1"></a><span class="fu">plot</span>(BOG_rain_2018_2019, </span>
<span id="cb130-3"><a href="introducción-modelos-pronóstico.html#cb130-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Precipitación total diaria Bogotá 2018-2019&#39;</span>, </span>
<span id="cb130-4"><a href="introducción-modelos-pronóstico.html#cb130-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Lluvia [mm]&#39;</span>,</span>
<span id="cb130-5"><a href="introducción-modelos-pronóstico.html#cb130-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>De la anterior gráfica se nota claramente, que aunque anteriormente no se encontraron datos faltantes / NA en el conjunto de datos seleccionados para la precipitación es notorio que entre marzo (mes 3) y agosto (mes 8) de 2019 se presentan de seguido registros de lluvia que son cero, aunque es de esperar que no lloverá todos los días del año en Bogotá, tampoco tiene sentido que se presenten cinco meses de sin registros de lluvia; lo anterior permite inferir que el sensor / pluviómetro presentó fallas en dichos meses y esto se confirma al revisar los datos en el <em>dataframe</em> que contiene ceros con un formato diferente (<code>int</code> 0 vs <code>dbl</code> 0.0) en el periodo en mención<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>.</p>
<p>La figura siguiente presenta la tendencia de la temperatura máxima diaria en Medellín y se observa fácilmente que no encuentran datos por fuera del rango de 20 a 33 ºC.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="introducción-modelos-pronóstico.html#cb131-1" tabindex="-1"></a><span class="co"># Plot xts Temperatura Medellín</span></span>
<span id="cb131-2"><a href="introducción-modelos-pronóstico.html#cb131-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023, </span>
<span id="cb131-3"><a href="introducción-modelos-pronóstico.html#cb131-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Temperatura máxima diaria Medellín 2022-2023&quot;</span>, </span>
<span id="cb131-4"><a href="introducción-modelos-pronóstico.html#cb131-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,</span>
<span id="cb131-5"><a href="introducción-modelos-pronóstico.html#cb131-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>Ahora con <code>lm</code> obtenemos la tendencia tanto para las series / ts para la precipitación y para la temperatura:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="introducción-modelos-pronóstico.html#cb132-1" tabindex="-1"></a><span class="co"># Tendencia precipitación Bogotá</span></span>
<span id="cb132-2"><a href="introducción-modelos-pronóstico.html#cb132-2" tabindex="-1"></a><span class="fu">plot</span>(BOG_rain_2018_2019_ts, </span>
<span id="cb132-3"><a href="introducción-modelos-pronóstico.html#cb132-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Tendencia Precipitación total diaria Bogotá 2018-2019&#39;</span>, </span>
<span id="cb132-4"><a href="introducción-modelos-pronóstico.html#cb132-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Lluvia [mm]&#39;</span>,</span>
<span id="cb132-5"><a href="introducción-modelos-pronóstico.html#cb132-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span>
<span id="cb132-6"><a href="introducción-modelos-pronóstico.html#cb132-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg=</span><span class="fu">lm</span>(BOG_rain_2018_2019_ts<span class="sc">~</span><span class="fu">time</span>(BOG_rain_2018_2019_ts)))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Se observa en la figura anterior una tendencia de la precipitación en Medellín que decrece desde cerca de los 4 mm de lluvia en enero de 2018 (t=0) a prácticamente 0 mm en diciembre de 2019 (t=730). Mientras que en la figura siguiente para la temperatura se aprecia una tendencia que aumenta cerca de dos grados desde de aproximadamente 26.5 ºC en t0 a 29 ºC en t730 en los años analizados.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="introducción-modelos-pronóstico.html#cb133-1" tabindex="-1"></a><span class="co"># Tendencia temperatura Medellín</span></span>
<span id="cb133-2"><a href="introducción-modelos-pronóstico.html#cb133-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023_ts, </span>
<span id="cb133-3"><a href="introducción-modelos-pronóstico.html#cb133-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Tendencia Temperatura máxima diaria Medellín 2022-2023&quot;</span>, </span>
<span id="cb133-4"><a href="introducción-modelos-pronóstico.html#cb133-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,</span>
<span id="cb133-5"><a href="introducción-modelos-pronóstico.html#cb133-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span>
<span id="cb133-6"><a href="introducción-modelos-pronóstico.html#cb133-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg=</span><span class="fu">lm</span>(MED_temp_2022_2023_ts<span class="sc">~</span><span class="fu">time</span>(MED_temp_2022_2023_ts)))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>A continuación se analizan las tendencias mensuales de la precipitación (la lluvia se suma para obtener los mm acumulados por mes) y la temperatura (se promedian los valores mensuales):</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="introducción-modelos-pronóstico.html#cb134-1" tabindex="-1"></a><span class="co"># Precipitación total acumulada mensual</span></span>
<span id="cb134-2"><a href="introducción-modelos-pronóstico.html#cb134-2" tabindex="-1"></a>BOG_rain_2018_2019_monthly <span class="ot">&lt;-</span> <span class="fu">apply.monthly</span>(BOG_rain_2018_2019, <span class="at">FUN=</span>sum)</span>
<span id="cb134-3"><a href="introducción-modelos-pronóstico.html#cb134-3" tabindex="-1"></a><span class="fu">str</span>(BOG_rain_2018_2019_monthly)</span></code></pre></div>
<pre><code>## An xts object on 2018-01-31 / 2019-12-31 containing: 
##   Data:    double [24, 1]
##   Columns: BOG
##   Index:   Date [24] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="introducción-modelos-pronóstico.html#cb136-1" tabindex="-1"></a><span class="fu">summary</span>(BOG_rain_2018_2019_monthly)</span></code></pre></div>
<pre><code>##      Index                 BOG        
##  Min.   :2018-01-31   Min.   :  0.00  
##  1st Qu.:2018-07-23   1st Qu.: 23.32  
##  Median :2019-01-15   Median : 45.00  
##  Mean   :2019-01-14   Mean   : 51.18  
##  3rd Qu.:2019-07-07   3rd Qu.: 63.20  
##  Max.   :2019-12-31   Max.   :199.70</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="introducción-modelos-pronóstico.html#cb138-1" tabindex="-1"></a>BOG_rain_2018_2019_monthly_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(BOG_rain_2018_2019_monthly, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2018</span>, <span class="dv">1</span>), <span class="at">frequency=</span><span class="dv">12</span>)</span>
<span id="cb138-2"><a href="introducción-modelos-pronóstico.html#cb138-2" tabindex="-1"></a></span>
<span id="cb138-3"><a href="introducción-modelos-pronóstico.html#cb138-3" tabindex="-1"></a><span class="co"># Tendencia precipitación acumulada mensual Bogotá</span></span>
<span id="cb138-4"><a href="introducción-modelos-pronóstico.html#cb138-4" tabindex="-1"></a><span class="fu">plot</span>(BOG_rain_2018_2019_monthly_ts, </span>
<span id="cb138-5"><a href="introducción-modelos-pronóstico.html#cb138-5" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Tendencia Precipitación total acumulada mensual Bogotá 2018-2019&#39;</span>, </span>
<span id="cb138-6"><a href="introducción-modelos-pronóstico.html#cb138-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Lluvia [mm]&#39;</span>,</span>
<span id="cb138-7"><a href="introducción-modelos-pronóstico.html#cb138-7" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span>
<span id="cb138-8"><a href="introducción-modelos-pronóstico.html#cb138-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg=</span><span class="fu">lm</span>(BOG_rain_2018_2019_monthly_ts<span class="sc">~</span><span class="fu">time</span>(BOG_rain_2018_2019_monthly_ts)))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>En la figura anterior se confirma que con los datos de abril, mayo, junio y julio de 2019 en el <em>dataset</em> se obtienen precipitaciones mensuales de cero milímetros, por lo que dichos meses se asumen como no válidos debido a fallas en el equipo de medición.</p>
<p>En la figura siguiente se presenta la tendencia de la temperatura máxima promedio mensual que presenta como era de esperar una línea creciente de aproximadamente de 26.5 a 29 ºC.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="introducción-modelos-pronóstico.html#cb139-1" tabindex="-1"></a><span class="co"># Temperatura máxima promedio mensual</span></span>
<span id="cb139-2"><a href="introducción-modelos-pronóstico.html#cb139-2" tabindex="-1"></a>MED_temp_2022_2023_monthly <span class="ot">&lt;-</span> <span class="fu">apply.monthly</span>(MED_temp_2022_2023, <span class="at">FUN=</span>mean)</span></code></pre></div>
<pre><code>## NOTE: `apply.monthly(..., FUN = mean)` operates by column, unlike other math
##   functions (e.g. median, sum, var, sd). Please use `FUN = colMeans` instead,
##   and use `FUN = function(x) mean(x)` to take the mean of all columns. Set
##   `options(xts.message.period.apply.mean = FALSE)` to suppress this message.</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="introducción-modelos-pronóstico.html#cb141-1" tabindex="-1"></a><span class="fu">str</span>(MED_temp_2022_2023_monthly)</span></code></pre></div>
<pre><code>## An xts object on 2022-01-31 / 2023-12-31 containing: 
##   Data:    double [24, 1]
##   Columns: MED
##   Index:   Date [24] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="introducción-modelos-pronóstico.html#cb143-1" tabindex="-1"></a><span class="fu">summary</span>(MED_temp_2022_2023_monthly)</span></code></pre></div>
<pre><code>##      Index                 MED       
##  Min.   :2022-01-31   Min.   :26.04  
##  1st Qu.:2022-07-23   1st Qu.:27.14  
##  Median :2023-01-15   Median :27.57  
##  Mean   :2023-01-14   Mean   :27.92  
##  3rd Qu.:2023-07-07   3rd Qu.:28.67  
##  Max.   :2023-12-31   Max.   :30.39</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="introducción-modelos-pronóstico.html#cb145-1" tabindex="-1"></a>MED_temp_2022_2023_monthly_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(MED_temp_2022_2023_monthly, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2022</span>, <span class="dv">1</span>), <span class="at">frequency=</span><span class="dv">12</span>)</span>
<span id="cb145-2"><a href="introducción-modelos-pronóstico.html#cb145-2" tabindex="-1"></a></span>
<span id="cb145-3"><a href="introducción-modelos-pronóstico.html#cb145-3" tabindex="-1"></a></span>
<span id="cb145-4"><a href="introducción-modelos-pronóstico.html#cb145-4" tabindex="-1"></a><span class="co"># Tendencia temperatura promedio mensual Medellín</span></span>
<span id="cb145-5"><a href="introducción-modelos-pronóstico.html#cb145-5" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023_monthly_ts, </span>
<span id="cb145-6"><a href="introducción-modelos-pronóstico.html#cb145-6" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Tendencia Temperatura máxima promedio mensual Medellín 2022-2023&quot;</span>, </span>
<span id="cb145-7"><a href="introducción-modelos-pronóstico.html#cb145-7" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,</span>
<span id="cb145-8"><a href="introducción-modelos-pronóstico.html#cb145-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span>
<span id="cb145-9"><a href="introducción-modelos-pronóstico.html#cb145-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg=</span><span class="fu">lm</span>(MED_temp_2022_2023_monthly_ts<span class="sc">~</span><span class="fu">time</span>(MED_temp_2022_2023_monthly_ts)))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>A continuación obtenemos el ciclo mensual para cada una de las variables estudiadas en las ciudades seleccionadas y se grafica con <code>aggregate</code>.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="introducción-modelos-pronóstico.html#cb146-1" tabindex="-1"></a><span class="co"># Ciclo lluvia Bogotá</span></span>
<span id="cb146-2"><a href="introducción-modelos-pronóstico.html#cb146-2" tabindex="-1"></a><span class="fu">cycle</span>(BOG_rain_2018_2019_monthly_ts)</span></code></pre></div>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 2018   1   2   3   4   5   6   7   8   9  10  11  12
## 2019   1   2   3   4   5   6   7   8   9  10  11  12</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="introducción-modelos-pronóstico.html#cb148-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">aggregate</span>(BOG_rain_2018_2019_monthly_ts, <span class="at">FUN=</span>mean), </span>
<span id="cb148-2"><a href="introducción-modelos-pronóstico.html#cb148-2" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Tendencia aggregate Precipitación total acumulada mensual Bogotá 2018-2019&#39;</span>, </span>
<span id="cb148-3"><a href="introducción-modelos-pronóstico.html#cb148-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Lluvia [mm]&#39;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Tanto en la gráfica anterior, como en la siguiente, en ambos casos se obtienen las mismas tendencias para la precipitación y la temperatura que las encontradas con <code>abline</code> y la regresión lineal con <code>lm</code>.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="introducción-modelos-pronóstico.html#cb149-1" tabindex="-1"></a><span class="co"># Ciclo temperatura Medellín</span></span>
<span id="cb149-2"><a href="introducción-modelos-pronóstico.html#cb149-2" tabindex="-1"></a><span class="fu">cycle</span>(MED_temp_2022_2023_monthly_ts)</span></code></pre></div>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 2022   1   2   3   4   5   6   7   8   9  10  11  12
## 2023   1   2   3   4   5   6   7   8   9  10  11  12</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="introducción-modelos-pronóstico.html#cb151-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">aggregate</span>(MED_temp_2022_2023_monthly_ts, <span class="at">FUN=</span>mean), </span>
<span id="cb151-2"><a href="introducción-modelos-pronóstico.html#cb151-2" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Tendencia aggregate Temperatura máxima mensual Medellín 2022-2023&quot;</span>, </span>
<span id="cb151-3"><a href="introducción-modelos-pronóstico.html#cb151-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Tiempo / Día&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Ahora se presenta la dispersión / comportamiento mensual por medio de boxplots para tanto de las precipitaciones en Bogotá, así como para las temperaturas en Medellín:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="introducción-modelos-pronóstico.html#cb152-1" tabindex="-1"></a><span class="co"># Boxpplot lluvia mensual Bogotá</span></span>
<span id="cb152-2"><a href="introducción-modelos-pronóstico.html#cb152-2" tabindex="-1"></a><span class="fu">boxplot</span>(BOG_rain_2018_2019_monthly_ts<span class="sc">~</span><span class="fu">cycle</span>(BOG_rain_2018_2019_monthly_ts),</span>
<span id="cb152-3"><a href="introducción-modelos-pronóstico.html#cb152-3" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Dispersion Precipitación total acumulada mensual Bogotá 2018-2019&quot;</span>, </span>
<span id="cb152-4"><a href="introducción-modelos-pronóstico.html#cb152-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Mes&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Lluvia [mm]&#39;</span>,</span>
<span id="cb152-5"><a href="introducción-modelos-pronóstico.html#cb152-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="introducción-modelos-pronóstico.html#cb153-1" tabindex="-1"></a><span class="co"># Boxplot temperatura mensual Medellín</span></span>
<span id="cb153-2"><a href="introducción-modelos-pronóstico.html#cb153-2" tabindex="-1"></a><span class="fu">boxplot</span>(MED_temp_2022_2023_monthly_ts<span class="sc">~</span><span class="fu">cycle</span>(MED_temp_2022_2023_monthly_ts),</span>
<span id="cb153-3"><a href="introducción-modelos-pronóstico.html#cb153-3" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Dispersion Temperatura máxima mensual Medellín 2022-2023&quot;</span>,</span>
<span id="cb153-4"><a href="introducción-modelos-pronóstico.html#cb153-4" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&#39;Mes&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,</span>
<span id="cb153-5"><a href="introducción-modelos-pronóstico.html#cb153-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>Tal como se refiere en los materiales de la unidad, se procede a probar la función logaritmo<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> para graficar nuevamente los datos de temperatura y evidenciar si se obtiene alguna mejora en la visualización de las series diarias y mensuales.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="introducción-modelos-pronóstico.html#cb154-1" tabindex="-1"></a><span class="co"># Logaritmo temperatura Medellín</span></span>
<span id="cb154-2"><a href="introducción-modelos-pronóstico.html#cb154-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(MED_temp_2022_2023), </span>
<span id="cb154-3"><a href="introducción-modelos-pronóstico.html#cb154-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Logaritmo Temperatura máxima diaria Medellín 2022-2023&quot;</span>, </span>
<span id="cb154-4"><a href="introducción-modelos-pronóstico.html#cb154-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Temperatura [°C]&#39;</span>,</span>
<span id="cb154-5"><a href="introducción-modelos-pronóstico.html#cb154-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="introducción-modelos-pronóstico.html#cb155-1" tabindex="-1"></a><span class="co"># Logaritmo temperatura mensual Medellín</span></span>
<span id="cb155-2"><a href="introducción-modelos-pronóstico.html#cb155-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(MED_temp_2022_2023_monthly_ts), </span>
<span id="cb155-3"><a href="introducción-modelos-pronóstico.html#cb155-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Logaritmo Temperatura máxima mensual Medellín 2022-2023&#39;</span>, </span>
<span id="cb155-4"><a href="introducción-modelos-pronóstico.html#cb155-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(Temperatura [°C])&#39;</span>,</span>
<span id="cb155-5"><a href="introducción-modelos-pronóstico.html#cb155-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
</div>
<div id="modelo-holt-winters" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Modelo Holt-Winters<a href="introducción-modelos-pronóstico.html#modelo-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ahora, aplicamos el modelo Holt-Winters para la serie mensual de temperatura<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> en Medellín obtenida en el presente capítulo.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="introducción-modelos-pronóstico.html#cb156-1" tabindex="-1"></a><span class="co"># Holt Winters log temperatura mensual Medellín</span></span>
<span id="cb156-2"><a href="introducción-modelos-pronóstico.html#cb156-2" tabindex="-1"></a>BOG_rain_2018_2019_monthly_HW <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(BOG_rain_2018_2019_monthly_ts, </span>
<span id="cb156-3"><a href="introducción-modelos-pronóstico.html#cb156-3" tabindex="-1"></a>                                             <span class="at">seasonal =</span> <span class="st">&quot;additive&quot;</span>)</span>
<span id="cb156-4"><a href="introducción-modelos-pronóstico.html#cb156-4" tabindex="-1"></a></span>
<span id="cb156-5"><a href="introducción-modelos-pronóstico.html#cb156-5" tabindex="-1"></a><span class="fu">plot</span>(BOG_rain_2018_2019_monthly_HW, </span>
<span id="cb156-6"><a href="introducción-modelos-pronóstico.html#cb156-6" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Ajuste con Holt-Winters Precipitación total acumulada mensual Bogotá 2018-2019&#39;</span>,</span>
<span id="cb156-7"><a href="introducción-modelos-pronóstico.html#cb156-7" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(Temperatura [°C])&#39;</span>,</span>
<span id="cb156-8"><a href="introducción-modelos-pronóstico.html#cb156-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="introducción-modelos-pronóstico.html#cb157-1" tabindex="-1"></a><span class="co"># Holt Winters log temperatura mensual Medellín</span></span>
<span id="cb157-2"><a href="introducción-modelos-pronóstico.html#cb157-2" tabindex="-1"></a>MED_temp_2022_2023_monthly_HW <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(<span class="fu">log</span>(MED_temp_2022_2023_monthly_ts), </span>
<span id="cb157-3"><a href="introducción-modelos-pronóstico.html#cb157-3" tabindex="-1"></a>                                             <span class="at">seasonal =</span> <span class="st">&quot;additive&quot;</span>)</span>
<span id="cb157-4"><a href="introducción-modelos-pronóstico.html#cb157-4" tabindex="-1"></a></span>
<span id="cb157-5"><a href="introducción-modelos-pronóstico.html#cb157-5" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023_monthly_HW, </span>
<span id="cb157-6"><a href="introducción-modelos-pronóstico.html#cb157-6" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Ajuste con Holt-Winters Temperatura máxima promedio mensual Medellín 2022-2023&#39;</span>,</span>
<span id="cb157-7"><a href="introducción-modelos-pronóstico.html#cb157-7" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(Temperatura [°C])&#39;</span>,</span>
<span id="cb157-8"><a href="introducción-modelos-pronóstico.html#cb157-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>A continuación se presentan la descomposición para el modelo obtenido anteriormente:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="introducción-modelos-pronóstico.html#cb158-1" tabindex="-1"></a><span class="co"># Descomposición Holt Winters log temperatura Medellín</span></span>
<span id="cb158-2"><a href="introducción-modelos-pronóstico.html#cb158-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(MED_temp_2022_2023_monthly_HW), </span>
<span id="cb158-3"><a href="introducción-modelos-pronóstico.html#cb158-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Descomposición con Holt-Winters Temperatura máxima promedio mensual Medellín 2022-2023&#39;</span>,</span>
<span id="cb158-4"><a href="introducción-modelos-pronóstico.html#cb158-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(Temperatura [°C])&#39;</span>,</span>
<span id="cb158-5"><a href="introducción-modelos-pronóstico.html#cb158-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
</div>
<div id="predicciones-iniciales" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Predicciones iniciales<a href="introducción-modelos-pronóstico.html#predicciones-iniciales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ahora que contamos con los modelos Holt Winters aplicados a la series mensuales de temperatura en Medellín, se procede a realizar unas predicciones iniciales para seis meses.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="introducción-modelos-pronóstico.html#cb159-1" tabindex="-1"></a><span class="co"># Predicción Holt Winters log temperatura Medellín</span></span>
<span id="cb159-2"><a href="introducción-modelos-pronóstico.html#cb159-2" tabindex="-1"></a>MED_temp_2022_2023_monthly_Pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(MED_temp_2022_2023_monthly_HW, <span class="dv">6</span>, <span class="at">prediction.interval =</span> <span class="cn">TRUE</span>)</span>
<span id="cb159-3"><a href="introducción-modelos-pronóstico.html#cb159-3" tabindex="-1"></a>MED_temp_2022_2023_monthly_Pred</span></code></pre></div>
<pre><code>##               fit      upr      lwr
## Jan 2024 3.378123 3.430217 3.326029
## Feb 2024 3.418200 3.471906 3.364494
## Mar 2024 3.372686 3.428214 3.317158
## Apr 2024 3.393397 3.450955 3.335838
## May 2024 3.451220 3.511015 3.391425
## Jun 2024 3.449746 3.511980 3.387513</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="introducción-modelos-pronóstico.html#cb161-1" tabindex="-1"></a><span class="co"># Gráfico Predicción Holt Winters log temperatura Medellín</span></span>
<span id="cb161-2"><a href="introducción-modelos-pronóstico.html#cb161-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023_monthly_HW, MED_temp_2022_2023_monthly_Pred, </span>
<span id="cb161-3"><a href="introducción-modelos-pronóstico.html#cb161-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Predicción con Holt-Winters Temperatura máxima promedio mensuañ Medellín 2022-2024&#39;</span>,</span>
<span id="cb161-4"><a href="introducción-modelos-pronóstico.html#cb161-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Fecha&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(Temperatura [°C])&#39;</span>,</span>
<span id="cb161-5"><a href="introducción-modelos-pronóstico.html#cb161-5" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;lightgreen&quot;</span>, <span class="st">&quot;green&quot;</span>))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Las predicciones encontradas con Holt-Winters siguen una tendencia creciente de la temperatura máxima mensual y parece no tener en cuenta el ciclo climático, pero es una primera aproximación que como todo prónostico se debe analizar en profundidad y tener claro los datos usados para generar predicciones futuras.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Los registros continuos de “ceros” van exactamente desde 2019-03-19 hasta 2019-08-07.<a href="introducción-modelos-pronóstico.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Debido a la presencia de ceros en los datos de precipitación no se aplica el logaritmo a dicha variable para evitar resultados infinitos / INF.<a href="introducción-modelos-pronóstico.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Como se anotó anteriormente, al aplicar al modelo <code>HoltWinters</code> a la precipitación mensual con registros de cero se obtiene error NA/NaN/Inf con <code>lm.fit</code><a href="introducción-modelos-pronóstico.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preprocesamiento-y-visualización.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
