<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 5 Modelos estacionarios en series de tiempo | Universidad Javeriana Cali Maestría en Ciencia de Datos</title>
  <meta name="description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 5 Modelos estacionarios en series de tiempo | Universidad Javeriana Cali Maestría en Ciencia de Datos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  <meta name="github-repo" content="raulfdocastro/SeriesTiempoPUJCali" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 5 Modelos estacionarios en series de tiempo | Universidad Javeriana Cali Maestría en Ciencia de Datos" />
  
  <meta name="twitter:description" content="Libro en Bookdown para la asignatura Análisis de Series de Tiempo - 20241 - B" />
  

<meta name="author" content="Joan Sebastián García Villa" />
<meta name="author" content="Laura Yohanna Bermúdez Murillo" />
<meta name="author" content="Raúl Fernando Castro Suárez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducción-modelos-pronóstico.html"/>
<link rel="next" href="regresión-en-series-de-tiempo.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="propuesta.html"><a href="propuesta.html"><i class="fa fa-check"></i><b>1</b> Propuesta Bookdown Grupo 7</a>
<ul>
<li class="chapter" data-level="1.1" data-path="propuesta.html"><a href="propuesta.html#tipo-de-datos"><i class="fa fa-check"></i><b>1.1</b> Tipo de datos</a></li>
<li class="chapter" data-level="1.2" data-path="propuesta.html"><a href="propuesta.html#importancia-del-pronóstico"><i class="fa fa-check"></i><b>1.2</b> Importancia del pronóstico</a></li>
<li class="chapter" data-level="1.3" data-path="propuesta.html"><a href="propuesta.html#fuente-de-datos"><i class="fa fa-check"></i><b>1.3</b> Fuente de datos</a></li>
<li class="chapter" data-level="1.4" data-path="propuesta.html"><a href="propuesta.html#consideraciones-finales"><i class="fa fa-check"></i><b>1.4</b> Consideraciones finales</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> Estructura de las series de tiempo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#variables-a-analizar"><i class="fa fa-check"></i><b>2.1</b> Variables a analizar</a></li>
<li class="chapter" data-level="2.2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#conjunto-de-datos"><i class="fa fa-check"></i><b>2.2</b> Conjunto de datos</a></li>
<li class="chapter" data-level="2.3" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#series-tiempo"><i class="fa fa-check"></i><b>2.3</b> Series de tiempo</a></li>
<li class="chapter" data-level="2.4" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#datos-faltantes"><i class="fa fa-check"></i><b>2.4</b> Datos faltantes</a></li>
<li class="chapter" data-level="2.5" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#EDA"><i class="fa fa-check"></i><b>2.5</b> Análisis exploratorio</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#boxplots"><i class="fa fa-check"></i><b>2.5.1</b> Boxplots</a></li>
<li class="chapter" data-level="2.5.2" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#histogramas"><i class="fa fa-check"></i><b>2.5.2</b> Histogramas</a></li>
<li class="chapter" data-level="2.5.3" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#análisis-por-años"><i class="fa fa-check"></i><b>2.5.3</b> Análisis por años</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estructura-de-las-series-de-tiempo.html"><a href="estructura-de-las-series-de-tiempo.html#observaciones-finales"><i class="fa fa-check"></i><b>2.6</b> Observaciones finales</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html"><i class="fa fa-check"></i><b>3</b> Preprocesamiento y visualización</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#medias-móviles"><i class="fa fa-check"></i><b>3.1</b> Medias móviles</a></li>
<li class="chapter" data-level="3.2" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#descomposición"><i class="fa fa-check"></i><b>3.2</b> Descomposición</a></li>
<li class="chapter" data-level="3.3" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#dickey-fuller-test"><i class="fa fa-check"></i><b>3.3</b> Dickey-Fuller Test</a></li>
<li class="chapter" data-level="3.4" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#funciones-de-autocorrelación-acf-y-pacf"><i class="fa fa-check"></i><b>3.4</b> Funciones de autocorrelación (ACF y PACF)</a></li>
<li class="chapter" data-level="3.5" data-path="preprocesamiento-y-visualización.html"><a href="preprocesamiento-y-visualización.html#rezagos"><i class="fa fa-check"></i><b>3.5</b> Rezagos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html"><i class="fa fa-check"></i><b>4</b> Introducción modelos pronóstico</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#tendencias-y-ciclos"><i class="fa fa-check"></i><b>4.1</b> Tendencias y ciclos</a></li>
<li class="chapter" data-level="4.2" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#modelo-holt-winters"><i class="fa fa-check"></i><b>4.2</b> Modelo Holt-Winters</a></li>
<li class="chapter" data-level="4.3" data-path="introducción-modelos-pronóstico.html"><a href="introducción-modelos-pronóstico.html#predicciones-iniciales"><i class="fa fa-check"></i><b>4.3</b> Predicciones iniciales</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html"><i class="fa fa-check"></i><b>5</b> Modelos estacionarios en series de tiempo</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#selección-de-series"><i class="fa fa-check"></i><b>5.1</b> Selección de series</a></li>
<li class="chapter" data-level="5.2" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#puntos-de-cambio"><i class="fa fa-check"></i><b>5.2</b> Puntos de cambio</a></li>
<li class="chapter" data-level="5.3" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#verificación-de-estacionariedad"><i class="fa fa-check"></i><b>5.3</b> Verificación de estacionariedad</a></li>
<li class="chapter" data-level="5.4" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#funciones-de-acf-y-pact"><i class="fa fa-check"></i><b>5.4</b> Funciones de ACF y PACT</a></li>
<li class="chapter" data-level="5.5" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#modelos-arima"><i class="fa fa-check"></i><b>5.5</b> Modelos ARIMA</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#predicciones-arima"><i class="fa fa-check"></i><b>5.5.1</b> Predicciones ARIMA</a></li>
<li class="chapter" data-level="5.5.2" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#predicciones-forecast"><i class="fa fa-check"></i><b>5.5.2</b> Predicciones forecast</a></li>
<li class="chapter" data-level="5.5.3" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#verificación-valores-atípicos"><i class="fa fa-check"></i><b>5.5.3</b> Verificación valores atípicos</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="modelos-estacionarios-en-series-de-tiempo.html"><a href="modelos-estacionarios-en-series-de-tiempo.html#observaciones-predicciones"><i class="fa fa-check"></i><b>5.6</b> Observaciones predicciones</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html"><i class="fa fa-check"></i><b>6</b> Regresión en series de tiempo</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html#selección-de-dataframes-para-regresión"><i class="fa fa-check"></i><b>6.1</b> Selección de dataframes para regresión</a></li>
<li class="chapter" data-level="6.2" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html#modelos-y-predicción-arima-ets-y-prophet"><i class="fa fa-check"></i><b>6.2</b> Modelos y predicción ARIMA, ETS y Prophet</a></li>
<li class="chapter" data-level="6.3" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html#comparación-de-modelos"><i class="fa fa-check"></i><b>6.3</b> Comparación de modelos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html#comparación-modelos-de-regresión-series-medellín"><i class="fa fa-check"></i><b>6.3.1</b> Comparación modelos de regresión series Medellín</a></li>
<li class="chapter" data-level="6.3.2" data-path="regresión-en-series-de-tiempo.html"><a href="regresión-en-series-de-tiempo.html#comparación-modelos-de-regresión-series-valledupar"><i class="fa fa-check"></i><b>6.3.2</b> Comparación modelos de regresión series Valledupar</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Universidad Javeriana Cali<br />
Maestría en Ciencia de Datos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-estacionarios-en-series-de-tiempo" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Capítulo 5</span> Modelos estacionarios en series de tiempo<a href="modelos-estacionarios-en-series-de-tiempo.html#modelos-estacionarios-en-series-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En el presente capítulo se aplica la metodología Box-Jenkins para identificar modelos autoregresivos integrados de media móvil (ARIMA) para analizar y predecir valores futuros de las series de tiempo estudiada en el Grupo. Con las series estudiadas en las <a href="introducción-modelos-pronóstico.html#predicciones-iniciales">Predicciones iniciales</a> se procede a trabajar en el presente capítulo.</p>
<div id="selección-de-series" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Selección de series<a href="modelos-estacionarios-en-series-de-tiempo.html#selección-de-series" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tal como se hizo en la unidad anterior, se trabajará en este capítulo con la temperatura máxima diaria a la cual es posible aplicar los métodos clásicos de series de tiempo. Tal como se vio en el análisis exploratorio inicial de las <a href="estructura-de-las-series-de-tiempo.html#series-tiempo">Series de tiempo</a>, por continuidad de los registros se trabajará con los datos de Valledupar en los años 2018 y 2019 y con los de Medellín entre 2022 y 2023. A continuación se presenta la descripción inicial de los datos, la clase de los objetos creados, el inicio y fin, su frecuencia, así como la cantidad de NA y un resumen estadístico para cada serie.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb169-1" tabindex="-1"></a><span class="co"># Serie xts Temperatura máxima diaria Valledupar 2018-2019</span></span>
<span id="cb169-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb169-2" tabindex="-1"></a>VUP_temp_2018_2019 <span class="ot">&lt;-</span> df_temp_max_ts[<span class="st">&quot;2018/2019&quot;</span>, <span class="st">&quot;VUP&quot;</span>]</span>
<span id="cb169-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb169-3" tabindex="-1"></a><span class="fu">str</span>(VUP_temp_2018_2019)</span></code></pre></div>
<pre><code>## An xts object on 2018-01-01 / 2019-12-31 containing: 
##   Data:    double [730, 1]
##   Columns: VUP
##   Index:   Date [730] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb171-1" tabindex="-1"></a><span class="fu">class</span>(VUP_temp_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb173-1" tabindex="-1"></a><span class="fu">start</span>(VUP_temp_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;2018-01-01&quot;</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb175-1" tabindex="-1"></a><span class="fu">end</span>(VUP_temp_2018_2019)</span></code></pre></div>
<pre><code>## [1] &quot;2019-12-31&quot;</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb177-1" tabindex="-1"></a><span class="fu">frequency</span>(VUP_temp_2018_2019)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb179-1" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(VUP_temp_2018_2019))</span></code></pre></div>
<pre><code>## VUP 
##   0</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb181-1" tabindex="-1"></a><span class="co"># Serie ts Temperatura máxima diaria Valledupar 2018-2019</span></span>
<span id="cb181-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb181-2" tabindex="-1"></a>VUP_temp_2018_2019_ts <span class="ot">&lt;-</span> <span class="fu">as.ts</span>(VUP_temp_2018_2019)</span>
<span id="cb181-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb181-3" tabindex="-1"></a><span class="fu">class</span>(VUP_temp_2018_2019_ts)</span></code></pre></div>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb183-1" tabindex="-1"></a><span class="fu">str</span>(VUP_temp_2018_2019_ts)</span></code></pre></div>
<pre><code>##  Time-Series [1:730] from 1 to 730: 34.2 32.3 33.5 33.4 32.8 34.2 33.9 34.8 34.4 33.3 ...</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb185-1" tabindex="-1"></a><span class="fu">summary</span>(VUP_temp_2018_2019_ts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   27.80   34.23   35.60   35.48   36.80   40.60</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb187-1" tabindex="-1"></a><span class="co"># Serie xts Temperatura máxima diaria Medellín 2022-2023</span></span>
<span id="cb187-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb187-2" tabindex="-1"></a>MED_temp_2022_2023 <span class="ot">&lt;-</span> df_temp_max_ts[<span class="st">&quot;2022/2023&quot;</span>, <span class="st">&quot;MED&quot;</span>]</span>
<span id="cb187-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb187-3" tabindex="-1"></a><span class="fu">str</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## An xts object on 2022-01-01 / 2023-12-31 containing: 
##   Data:    double [730, 1]
##   Columns: MED
##   Index:   Date [730] (TZ: &quot;UTC&quot;)</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb189-1" tabindex="-1"></a><span class="fu">class</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb191-1" tabindex="-1"></a><span class="fu">start</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;2022-01-01&quot;</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb193-1" tabindex="-1"></a><span class="fu">end</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] &quot;2023-12-31&quot;</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb195-1" tabindex="-1"></a><span class="fu">frequency</span>(MED_temp_2022_2023)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb197-1" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(MED_temp_2022_2023))</span></code></pre></div>
<pre><code>## MED 
##   0</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb199-1" tabindex="-1"></a><span class="co"># Serie ts Temperatura máxima diaria Medellín 2022-2023</span></span>
<span id="cb199-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb199-2" tabindex="-1"></a>MED_temp_2022_2023_ts <span class="ot">&lt;-</span> <span class="fu">as.ts</span>(MED_temp_2022_2023)</span>
<span id="cb199-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb199-3" tabindex="-1"></a><span class="fu">class</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb201-1" tabindex="-1"></a><span class="fu">str</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>##  Time-Series [1:730] from 1 to 730: 27.4 26.4 27.8 28 28.2 26 25 26.8 27.4 24.6 ...</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb203-1" tabindex="-1"></a><span class="fu">summary</span>(MED_temp_2022_2023_ts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   20.60   26.50   28.00   27.93   29.40   32.60</code></pre>
<p>Luego de obtener la descripción de las series, se procede como se ha hecho anteriormente a graficarlas:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-1" tabindex="-1"></a><span class="co"># Plot ts Temperatura Valledupar</span></span>
<span id="cb205-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-2" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_2018_2019_ts, </span>
<span id="cb205-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Temperatura máxima diaria Valledupar 2018-2019&quot;</span>, </span>
<span id="cb205-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>,</span>
<span id="cb205-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;orange&quot;</span>)</span>
<span id="cb205-6"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb205-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(VUP_temp_2018_2019), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty=</span><span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>Es importante notar que el comportamiento de la temperatura máxima diaria en Valledupar varía entre cerca de los 28 ºC a los 40 ºC. En la figura anterior se aprecia que el promedio de la serie se encuentra cercana a los 35.5 grados Celsius.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-1" tabindex="-1"></a><span class="co"># Plot xts Temperatura Medellín</span></span>
<span id="cb206-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_2022_2023_ts, </span>
<span id="cb206-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Temperatura máxima diaria Medellín 2022-2023&quot;</span>, </span>
<span id="cb206-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>,</span>
<span id="cb206-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-5" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;lightgreen&quot;</span>)</span>
<span id="cb206-6"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb206-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(MED_temp_2022_2023), <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lty=</span><span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>Como ya se había descrito para Medellín en capítulo 4 en el numeral de <a href="introducción-modelos-pronóstico.html#tendencias-y-ciclos">Tendencias y ciclos</a>, la temperatura máxima diaria en la ciudad en los años 2022 y 2023 varía entre los 20 ºC y los 33 ºC, mientras que su promedio se encuentra cerca de los 28 ºC.</p>
</div>
<div id="puntos-de-cambio" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Puntos de cambio<a href="modelos-estacionarios-en-series-de-tiempo.html#puntos-de-cambio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ahora, encontramos los puntos de cambio de las series con la función <code>cpt.mean</code>:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb207-1" tabindex="-1"></a><span class="co"># Change points Valledupar</span></span>
<span id="cb207-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb207-2" tabindex="-1"></a>VUP_temp_cpt <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(VUP_temp_2018_2019_ts, <span class="at">method =</span> <span class="st">&quot;AMOC&quot;</span>) </span>
<span id="cb207-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb207-3" tabindex="-1"></a><span class="fu">cpts</span>(VUP_temp_cpt)</span></code></pre></div>
<pre><code>## [1] 623</code></pre>
<p>Se puede apreciar que el punto de cambio en la serie de temperatura máxima diaria en Valledupar entre los años 2018 y 2019 se presenta el día 623, es decir, el 16 de septiembre de 2019.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb209-1" tabindex="-1"></a><span class="co"># Change points Medellín</span></span>
<span id="cb209-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb209-2" tabindex="-1"></a>MED_temp_cpt <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(MED_temp_2022_2023_ts, <span class="at">method =</span> <span class="st">&quot;AMOC&quot;</span>) </span>
<span id="cb209-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb209-3" tabindex="-1"></a><span class="fu">cpts</span>(MED_temp_cpt)</span></code></pre></div>
<pre><code>## [1] 485</code></pre>
<p>Mientras, que para Medellín en la serie de los años 2022 y 2023, el punto de cambio en la temperatura máxima diaria se encuentra según la función <code>cpt.mean</code> el día 485, que corresponde a 1 de mayo de 2023.</p>
<p>Finalmente obtenemos con <code>plot</code> las gráficas para cada punto de cambio calculado anteriormente:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb211-1" tabindex="-1"></a><span class="co"># Plot change point Valledupar</span></span>
<span id="cb211-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb211-2" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_cpt, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">cpt.col =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">cpt.width =</span> <span class="dv">3</span>,</span>
<span id="cb211-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb211-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Punto cambio Temperatura máxima Valledupar&quot;</span>, </span>
<span id="cb211-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb211-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>Tal como se calculó en Valledupar es claro el cambio / disminución en la línea naranja cerca del día 623.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb212-1" tabindex="-1"></a><span class="co"># Plot change point Medellín</span></span>
<span id="cb212-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb212-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_cpt, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">cpt.col =</span> <span class="st">&quot;lightgreen&quot;</span>, <span class="at">cpt.width =</span> <span class="dv">3</span>,</span>
<span id="cb212-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb212-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Punto cambio Temperatura máxima Medellín&quot;</span>, </span>
<span id="cb212-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb212-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Nuevamente, tal como se calculó con <code>cpt.mean</code> para Medellín se aprecia en la figura anterior el cambio / aumento en la línea verde claro cerca del día 485.</p>
</div>
<div id="verificación-de-estacionariedad" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Verificación de estacionariedad<a href="modelos-estacionarios-en-series-de-tiempo.html#verificación-de-estacionariedad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Por último, procedemos a verificar si las series son estacionarias con la función <code>adf.test</code>:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb213-1" tabindex="-1"></a><span class="co"># ADF Valledupar</span></span>
<span id="cb213-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb213-2" tabindex="-1"></a><span class="fu">adf.test</span>(VUP_temp_2018_2019_ts, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;stationary&quot;</span>, <span class="st">&quot;explosive&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  VUP_temp_2018_2019_ts
## Dickey-Fuller = -4.3478, Lag order = 8, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb215-1" tabindex="-1"></a><span class="co"># ADF Medellín</span></span>
<span id="cb215-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb215-2" tabindex="-1"></a><span class="fu">adf.test</span>(MED_temp_2022_2023_ts, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;stationary&quot;</span>, <span class="st">&quot;explosive&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  MED_temp_2022_2023_ts
## Dickey-Fuller = -6.0864, Lag order = 8, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<p>Como en ambos casos, el p-value es menor que 0.05 (en cada caso 0.01) las series de temperatura máxima diaria analizadas <strong>son estacionarias</strong>.</p>
</div>
<div id="funciones-de-acf-y-pact" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Funciones de ACF y PACT<a href="modelos-estacionarios-en-series-de-tiempo.html#funciones-de-acf-y-pact" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tal como se realizó en el Capítulo 3 para la lluvia en la sección <a href="preprocesamiento-y-visualización.html#funciones-de-autocorrelación-acf-y-pacf">Funciones de autocorrelación (ACF y PACF)</a>, ahora se aplican las funciones de autocorrelación <code>acf</code> y <code>pacf</code> y se obtienen las gráficas respectivas para las series de temperatura seleccionadas de Valledupar y Medellín:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb217-1" tabindex="-1"></a><span class="co"># ACF y PACF Valledupar</span></span>
<span id="cb217-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb217-2" tabindex="-1"></a><span class="fu">acf</span>(VUP_temp_2018_2019_ts, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>,</span>
<span id="cb217-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb217-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;ACF Temperatura máxima Valledupar&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb218-1" tabindex="-1"></a><span class="fu">pacf</span>(VUP_temp_2018_2019_ts, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>,</span>
<span id="cb218-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb218-2" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;PACF Temperatura máxima Valledupar&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-73-2.png" width="672" /></p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb219-1" tabindex="-1"></a><span class="co"># ACF y PACF Medellín</span></span>
<span id="cb219-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb219-2" tabindex="-1"></a><span class="fu">acf</span>(MED_temp_2022_2023_ts, <span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>,</span>
<span id="cb219-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb219-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;ACF Temperatura máxima Medellín&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb220-1" tabindex="-1"></a><span class="fu">pacf</span>(MED_temp_2022_2023_ts, <span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>,</span>
<span id="cb220-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb220-2" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;PACF Temperatura máxima Medellín&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-74-2.png" width="672" /></p>
</div>
<div id="modelos-arima" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Modelos ARIMA<a href="modelos-estacionarios-en-series-de-tiempo.html#modelos-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ahora, se procede a aplicar la función <code>auto.arima</code>, para encontrar el modelo de ajuste para las series de temperaturas máximas de Valledupar y Medellín:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb221-1" tabindex="-1"></a><span class="co"># Auto ARIMA Valledupar</span></span>
<span id="cb221-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb221-2" tabindex="-1"></a>VUP_temp_model <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(VUP_temp_2018_2019_ts)</span>
<span id="cb221-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb221-3" tabindex="-1"></a>VUP_temp_model</span></code></pre></div>
<pre><code>## Series: VUP_temp_2018_2019_ts 
## ARIMA(3,0,1) with non-zero mean 
## 
## Coefficients:
##          ar1      ar2      ar3      ma1     mean
##       1.2715  -0.2007  -0.0910  -0.8465  35.4347
## s.e.  0.0563   0.0609   0.0429   0.0413   0.4139
## 
## sigma^2 = 2.329:  log likelihood = -1342.36
## AIC=2696.72   AICc=2696.84   BIC=2724.28</code></pre>
<p>El ajuste para el modelo de la temperatura máxima diaria de Valledupar se encuentra en ARIMA(3,0,1), mientras que como se observa a continuación el de Medellín se calcula en ARIMA(2,1,3).</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb223-1" tabindex="-1"></a><span class="co"># Auto ARIMA Medellín</span></span>
<span id="cb223-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb223-2" tabindex="-1"></a>MED_temp_model <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(MED_temp_2022_2023_ts)</span>
<span id="cb223-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb223-3" tabindex="-1"></a>MED_temp_model</span></code></pre></div>
<pre><code>## Series: MED_temp_2022_2023_ts 
## ARIMA(2,1,3) 
## 
## Coefficients:
##           ar1     ar2      ma1      ma2     ma3
##       -0.4122  0.5378  -0.2224  -0.9113  0.1923
## s.e.   0.1184  0.1156   0.1347   0.0426  0.1196
## 
## sigma^2 = 2.838:  log likelihood = -1412.96
## AIC=2837.91   AICc=2838.03   BIC=2865.46</code></pre>
<div id="predicciones-arima" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Predicciones ARIMA<a href="modelos-estacionarios-en-series-de-tiempo.html#predicciones-arima" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Con los modelos ARIMA listos, con la función <code>forecast</code>y usando los modelos anteriores se procede a predecir 30 días para cada una de las series de Valledupar y Medellín:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb225-1" tabindex="-1"></a><span class="co"># Forecast ARIMA Valledupar</span></span>
<span id="cb225-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb225-2" tabindex="-1"></a>VUP_temp_arima <span class="ot">&lt;-</span> <span class="fu">forecast</span>(VUP_temp_model, <span class="at">h =</span> <span class="dv">30</span>,<span class="at">level=</span><span class="dv">95</span>)</span>
<span id="cb225-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb225-3" tabindex="-1"></a>VUP_temp_arima</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 95    Hi 95
## 731       35.38321 32.39203 38.37439
## 732       35.40162 32.15150 38.65173
## 733       35.46981 32.06462 38.87499
## 734       35.49066 32.00074 38.98058
## 735       35.50181 31.95145 39.05217
## 736       35.50560 31.90761 39.10360
## 737       35.50629 31.86778 39.14479
## 738       35.50538 31.83104 39.17973
## 739       35.50375 31.79699 39.21051
## 740       35.50179 31.76536 39.23822
## 741       35.49971 31.73595 39.26347
## 742       35.49761 31.70859 39.28663
## 743       35.49554 31.68312 39.30795
## 744       35.49351 31.65939 39.32763
## 745       35.49154 31.63727 39.34580
## 746       35.48962 31.61665 39.36260
## 747       35.48778 31.59741 39.37814
## 748       35.48599 31.57946 39.39251
## 749       35.48426 31.56270 39.40582
## 750       35.48259 31.54705 39.41813
## 751       35.48097 31.53242 39.42953
## 752       35.47941 31.51875 39.44008
## 753       35.47790 31.50596 39.44984
## 754       35.47645 31.49401 39.45889
## 755       35.47504 31.48282 39.46726
## 756       35.47368 31.47235 39.47500
## 757       35.47236 31.46255 39.48218
## 758       35.47109 31.45338 39.48881
## 759       35.46987 31.44478 39.49496
## 760       35.46868 31.43672 39.50064</code></pre>
<p>Se encuentra que para Valledupar se obtienen predicciones con <code>auto.arima</code> muy cercanas, entre 35.38 y 35.51 ºC, con sola una variación de 0.12 grados Celsius, por lo realmente son prácticamente constantes (en 35.4 o 35.5 ºC). El promedio de los <em>forecasts</em> <code>auto.arima</code> es de 35.48 ºC (la media de toda la serie de tiempo).</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb227-1" tabindex="-1"></a><span class="co"># Forecast ARIMA Medellín</span></span>
<span id="cb227-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb227-2" tabindex="-1"></a>MED_temp_arima <span class="ot">&lt;-</span> <span class="fu">forecast</span>(MED_temp_model, <span class="at">h =</span> <span class="dv">30</span>,<span class="at">level=</span><span class="dv">95</span>)</span>
<span id="cb227-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb227-3" tabindex="-1"></a>MED_temp_arima</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 95    Hi 95
## 731       28.80578 25.50406 32.10750
## 732       28.92633 25.41118 32.44147
## 733       28.73615 25.12274 32.34956
## 734       28.87938 25.23192 32.52684
## 735       28.71806 25.04432 32.39181
## 736       28.86159 25.17718 32.54600
## 737       28.71567 25.01790 32.41343
## 738       28.85301 25.14901 32.55701
## 739       28.71792 25.00380 32.43203
## 740       28.84747 25.12818 32.56676
## 741       28.72141 24.99304 32.44978
## 742       28.84305 25.10974 32.57635
## 743       28.72511 24.98316 32.46706
## 744       28.83914 25.09227 32.58601
## 745       28.72871 24.97343 32.48400
## 746       28.83556 25.07531 32.59581
## 747       28.73212 24.96364 32.50061
## 748       28.83222 25.05870 32.60575
## 749       28.73533 24.95373 32.51694
## 750       28.82911 25.04240 32.61582
## 751       28.73835 24.94369 32.53300
## 752       28.82619 25.02637 32.62601
## 753       28.74117 24.93352 32.54881
## 754       28.82346 25.01059 32.63633
## 755       28.74381 24.92323 32.56439
## 756       28.82090 24.99505 32.64675
## 757       28.74629 24.91284 32.57974
## 758       28.81850 24.97973 32.65728
## 759       28.74861 24.90234 32.59488
## 760       28.81626 24.96462 32.66790</code></pre>
<p>Al igual que la predicción anterior, para Medellín se obtienen valores casi constantes con <code>auto.arima</code> y <code>forecast</code> muy cercanos entre ellos (28.7 ºC - 28.9 ºC), con sola una variación de 0.21 ºC. El promedio de dichas predicciones es 28.79 ºC.</p>
<p>A continuación, se grafican con <code>plot</code> las predicciones <code>auto.arima</code> obtenidas para Valledupar y Medellín:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb229-1" tabindex="-1"></a><span class="co"># Plot forecast Valledupar</span></span>
<span id="cb229-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb229-2" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_arima, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>,</span>
<span id="cb229-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb229-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predicción ARIMA Temperatura máxima Valledupar&quot;</span>, </span>
<span id="cb229-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb229-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb229-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb229-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(VUP_temp_2018_2019), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>En la figura anterior, se aprecia poca variabilidad en la línea azul de la predicción para Valledupar y se nota claramente que los valores son en esencia la media de la serie de tiempo.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb230-1" tabindex="-1"></a><span class="co"># Plot forecast Medellín</span></span>
<span id="cb230-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb230-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_arima, <span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>, </span>
<span id="cb230-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb230-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predicción ARIMA Temperatura máxima Medellín&quot;</span>, </span>
<span id="cb230-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb230-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb230-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb230-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(MED_temp_2022_2023), <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>En Medellín, se aprecia para predicción prácticamente una línea recta, aunque esta vez más cercana a la media después del punto de cambio que a la media de toda la serie.</p>
<div id="cálculos-residuales" class="section level4 hasAnchor" number="5.5.1.1">
<h4><span class="header-section-number">5.5.1.1</span> Cálculos residuales<a href="modelos-estacionarios-en-series-de-tiempo.html#cálculos-residuales" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Ahora para las predicciones ARIMA, se estiman los residuales y se grafican con <code>qqnorm</code>.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb231-1" tabindex="-1"></a><span class="co"># Residuales Valledupar</span></span>
<span id="cb231-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb231-2" tabindex="-1"></a>VUP_temp_res <span class="ot">=</span> VUP_temp_arima<span class="sc">$</span>residuals</span>
<span id="cb231-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb231-3" tabindex="-1"></a><span class="fu">qqnorm</span>(VUP_temp_res)</span>
<span id="cb231-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb231-4" tabindex="-1"></a><span class="fu">qqline</span>(VUP_temp_res)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb232-1" tabindex="-1"></a><span class="co"># Residuales Medellín</span></span>
<span id="cb232-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb232-2" tabindex="-1"></a>MED_temp_res <span class="ot">=</span> MED_temp_arima<span class="sc">$</span>residuals</span>
<span id="cb232-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb232-3" tabindex="-1"></a><span class="fu">qqnorm</span>(MED_temp_res)</span>
<span id="cb232-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb232-4" tabindex="-1"></a><span class="fu">qqline</span>(MED_temp_res)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>A continuación, se procede a comprobar la normalidad de los modelos ARIMA inicialmente aplicando las pruebas de Shapiro-Wilk con la función <code>shapiro.test</code>.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb233-1" tabindex="-1"></a><span class="co"># Shapiro-Wilk Test Valledupar</span></span>
<span id="cb233-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb233-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(VUP_temp_res)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  VUP_temp_res
## W = 0.96438, p-value = 2.49e-12</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb235-1" tabindex="-1"></a><span class="co"># Shapiro-Wilk Test Medellín</span></span>
<span id="cb235-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb235-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(MED_temp_res)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  MED_temp_res
## W = 0.97552, p-value = 1.051e-09</code></pre>
<p>Ambos p-values son muy pequeños cercanos a 2.5E-12 y 1E-9 (por lo tanto mucho menor que 0.05), lo que indica que los modelos ARIMA para ambas ciudades no siguen una distribución normal.</p>
<p>Finalmente, se aplican las pruebas Box-Pierce / Ljung-Box con la función <code>Box.test</code> para evaluar la independencia de los residuos.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb237-1" tabindex="-1"></a><span class="co"># Box-Pierce Test Valledupar</span></span>
<span id="cb237-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb237-2" tabindex="-1"></a><span class="fu">Box.test</span>(VUP_temp_res, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;Box-Pierce&quot;</span>, <span class="st">&quot;Ljung-Box&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Box-Pierce test
## 
## data:  VUP_temp_res
## X-squared = 0.0055686, df = 1, p-value = 0.9405</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb239-1" tabindex="-1"></a><span class="co"># Box-Pierce Test Medellín</span></span>
<span id="cb239-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb239-2" tabindex="-1"></a><span class="fu">Box.test</span>(MED_temp_res, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;Box-Pierce&quot;</span>, <span class="st">&quot;Ljung-Box&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Box-Pierce test
## 
## data:  MED_temp_res
## X-squared = 0.0079384, df = 1, p-value = 0.929</code></pre>
<p>Los resultados de Box-Pierce, presentan p-values mayores a 0.9 (evidentemente por encima de 0.05), por lo tanto, no hay evidencia de autocorrelación significativa en los residuos de los modelos ARIMA y son independientes tanto para Valledupar, como para Medellín.</p>
</div>
</div>
<div id="predicciones-forecast" class="section level3 hasAnchor" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Predicciones forecast<a href="modelos-estacionarios-en-series-de-tiempo.html#predicciones-forecast" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora para comparar, se procede a predecir con la función <code>forecast</code> con un horizonte 30 días usando directamente cada una de las series de temperatura estudiadas:</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb241-1" tabindex="-1"></a><span class="co"># Forecast ts Valledupar</span></span>
<span id="cb241-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb241-2" tabindex="-1"></a>VUP_temp_pred <span class="ot">&lt;-</span> <span class="fu">forecast</span>(VUP_temp_2018_2019_ts, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb241-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb241-3" tabindex="-1"></a>VUP_temp_pred</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 731       35.44583 33.43742 37.45424 32.37423 38.51742
## 732       35.44583 33.29529 37.59637 32.15687 38.73479
## 733       35.44583 33.16199 37.72967 31.95300 38.93866
## 734       35.44583 33.03605 37.85561 31.76039 39.13127
## 735       35.44583 32.91637 37.97528 31.57736 39.31430
## 736       35.44583 32.80211 38.08955 31.40261 39.48905
## 737       35.44583 32.69258 38.19907 31.23510 39.65655
## 738       35.44583 32.58725 38.30441 31.07401 39.81765
## 739       35.44583 32.48566 38.40599 30.91865 39.97301
## 740       35.44583 32.38745 38.50421 30.76844 40.12322
## 741       35.44583 32.29229 38.59937 30.62291 40.26875
## 742       35.44583 32.19992 38.69173 30.48165 40.41001
## 743       35.44583 32.11011 38.78155 30.34429 40.54737
## 744       35.44583 32.02266 38.86900 30.21054 40.68112
## 745       35.44583 31.93738 38.95428 30.08012 40.81154
## 746       35.44583 31.85413 39.03753 29.95279 40.93887
## 747       35.44583 31.77276 39.11890 29.82835 41.06330
## 748       35.44583 31.69316 39.19850 29.70661 41.18505
## 749       35.44583 31.61521 39.27645 29.58740 41.30426
## 750       35.44583 31.53881 39.35284 29.47056 41.42109
## 751       35.44583 31.46388 39.42777 29.35597 41.53569
## 752       35.44583 31.39034 39.50132 29.24349 41.64816
## 753       35.44583 31.31811 39.57355 29.13302 41.75864
## 754       35.44583 31.24711 39.64454 29.02445 41.86721
## 755       35.44583 31.17730 39.71435 28.91768 41.97398
## 756       35.44583 31.10862 39.78304 28.81263 42.07902
## 757       35.44583 31.04100 39.85066 28.70922 42.18244
## 758       35.44583 30.97440 39.91725 28.60737 42.28428
## 759       35.44583 30.90879 39.98287 28.50702 42.38464
## 760       35.44583 30.84411 40.04755 28.40810 42.48356</code></pre>
<p>Aunque se obtienen predicciones / forecasting sin problemas, se puede apreciar fácilmente que el modelo pronostica para la temperatura máxima diaria en Valledupar un valor constante de 35.4 ºC para todo el mes / 30 días siguientes.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb243-1" tabindex="-1"></a><span class="co"># Forecast ts Medellín</span></span>
<span id="cb243-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb243-2" tabindex="-1"></a>MED_temp_pred <span class="ot">&lt;-</span> <span class="fu">forecast</span>(MED_temp_2022_2023_ts, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb243-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb243-3" tabindex="-1"></a>MED_temp_pred</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 731       28.32534 26.09965 30.55104 24.92143 31.72926
## 732       28.32534 26.03224 30.61845 24.81834 31.83235
## 733       28.32534 25.96675 30.68394 24.71819 31.93250
## 734       28.32534 25.90304 30.74765 24.62075 32.02994
## 735       28.32534 25.84096 30.80973 24.52580 32.12489
## 736       28.32534 25.78039 30.87030 24.43317 32.21752
## 737       28.32534 25.72123 30.92946 24.34270 32.30799
## 738       28.32534 25.66339 30.98730 24.25423 32.39646
## 739       28.32534 25.60677 31.04392 24.16765 32.48304
## 740       28.32534 25.55132 31.09937 24.08283 32.56786
## 741       28.32534 25.49694 31.15375 23.99968 32.65101
## 742       28.32534 25.44360 31.20709 23.91809 32.73259
## 743       28.32534 25.39122 31.25947 23.83799 32.81270
## 744       28.32534 25.33977 31.31092 23.75930 32.89139
## 745       28.32534 25.28918 31.36151 23.68193 32.96876
## 746       28.32534 25.23942 31.41127 23.60584 33.04485
## 747       28.32534 25.19046 31.46023 23.53095 33.11974
## 748       28.32534 25.14224 31.50845 23.45721 33.19348
## 749       28.32534 25.09475 31.55594 23.38458 33.26611
## 750       28.32534 25.04794 31.60275 23.31299 33.33770
## 751       28.32534 25.00180 31.64889 23.24242 33.40827
## 752       28.32534 24.95628 31.69441 23.17281 33.47788
## 753       28.32534 24.91138 31.73931 23.10413 33.54656
## 754       28.32534 24.86705 31.78364 23.03634 33.61435
## 755       28.32534 24.82329 31.82740 22.96941 33.68128
## 756       28.32534 24.78006 31.87063 22.90330 33.74739
## 757       28.32534 24.73736 31.91333 22.83800 33.81269
## 758       28.32534 24.69516 31.95553 22.77346 33.87723
## 759       28.32534 24.65344 31.99725 22.70966 33.94103
## 760       28.32534 24.61220 32.03849 22.64657 34.00411</code></pre>
<p>Al igual que con Valledupar, los pronósticos de Medellín son constantes en 28.3 ºC para todo el horizonte de 30 días solicitado al modelo.</p>
<p>Para finalizar, a continuación se grafican con <code>plot</code> las predicciones encontradas para Valledupar y Medellín:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb245-1" tabindex="-1"></a><span class="co"># Plot forecast Valledupar</span></span>
<span id="cb245-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb245-2" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_pred, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>,</span>
<span id="cb245-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb245-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Forecast Temperatura máxima Valledupar&quot;</span>, </span>
<span id="cb245-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb245-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb245-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb245-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(VUP_temp_2018_2019), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>Como era de esperar, se obtiene una línea horizontal de la predicción que no varía par Valledupar alrededor de los 35 grados Celsius.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb246-1" tabindex="-1"></a><span class="co"># Plot forecast Medellín</span></span>
<span id="cb246-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb246-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_pred, <span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>, </span>
<span id="cb246-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb246-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Forecast Temperatura máxima Medellín&quot;</span>, </span>
<span id="cb246-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb246-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb246-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb246-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(MED_temp_2022_2023), <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>La gráfica anterior presenta el pronóstico para Medellín que como se ha calculado, se encuentra cerca de los 28 ºC.</p>
</div>
<div id="verificación-valores-atípicos" class="section level3 hasAnchor" number="5.5.3">
<h3><span class="header-section-number">5.5.3</span> Verificación valores atípicos<a href="modelos-estacionarios-en-series-de-tiempo.html#verificación-valores-atípicos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para terminar, con la función <code>tso</code> de la librería <code>tsoutliers</code>, se validan los ARIMA y grafican los efectos de los valores atípicos / <em>outliers</em> en las series:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb247-1" tabindex="-1"></a><span class="co"># Outliers Valledupar</span></span>
<span id="cb247-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb247-2" tabindex="-1"></a>VUP_temp_outliers <span class="ot">&lt;-</span> <span class="fu">tso</span>(VUP_temp_2018_2019_ts)</span>
<span id="cb247-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb247-3" tabindex="-1"></a>VUP_temp_outliers</span></code></pre></div>
<pre><code>## Series: VUP_temp_2018_2019_ts 
## Regression with ARIMA(1,0,1) errors 
## 
## Coefficients:
##          ar1      ma1  intercept    TC226    AO555    TC593
##       0.9255  -0.5371    35.5162  -6.8913  -7.6706  -5.7097
## s.e.  0.0193   0.0469     0.3310   1.3540   1.3296   1.3545
## 
## sigma^2 = 2.152:  log likelihood = -1312.92
## AIC=2639.84   AICc=2639.99   BIC=2671.99
## 
## Outliers:
##   type ind time coefhat  tstat
## 1   TC 226  226  -6.891 -5.090
## 2   AO 555  555  -7.671 -5.769
## 3   TC 593  593  -5.710 -4.215</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb249-1" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_outliers,</span>
<span id="cb249-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb249-2" tabindex="-1"></a>     <span class="at">args.lines.y =</span> <span class="fu">list</span>(<span class="at">col =</span> <span class="st">&quot;orange&quot;</span>),</span>
<span id="cb249-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb249-3" tabindex="-1"></a>     <span class="at">args.lines.yadj =</span> <span class="fu">list</span>(<span class="at">col =</span> <span class="st">&quot;orangered&quot;</span>))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p>En el caso de Valledupar, la función <code>tso</code> encuentra tres outliers, mientras como se aprecia a continuación para Medellín solamente uno. Ahora, <code>tso</code> encuentra el ajuste de la serie de Valledupar sin atípicos en ARIMA(1,0,1) y para Medellín en ARIMA(1,1,1).</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb250-1" tabindex="-1"></a><span class="co"># Outliers Medellín</span></span>
<span id="cb250-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb250-2" tabindex="-1"></a>MED_temp_outliers <span class="ot">&lt;-</span> <span class="fu">tso</span>(MED_temp_2022_2023_ts)</span>
<span id="cb250-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb250-3" tabindex="-1"></a>MED_temp_outliers</span></code></pre></div>
<pre><code>## Series: MED_temp_2022_2023_ts 
## Regression with ARIMA(1,1,1) errors 
## 
## Coefficients:
##          ar1      ma1     AO50
##       0.3442  -0.9407  -7.1941
## s.e.  0.0452   0.0225   1.5369
## 
## sigma^2 = 2.78:  log likelihood = -1406.29
## AIC=2820.58   AICc=2820.63   BIC=2838.94
## 
## Outliers:
##   type ind time coefhat  tstat
## 1   AO  50   50  -7.194 -4.681</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb252-1" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_outliers,</span>
<span id="cb252-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb252-2" tabindex="-1"></a>     <span class="at">args.lines.y =</span> <span class="fu">list</span>(<span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>),</span>
<span id="cb252-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb252-3" tabindex="-1"></a>     <span class="at">args.lines.yadj =</span> <span class="fu">list</span>(<span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>))</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>Ahora se realizan las predicciones con <code>forecast</code>, usando <code>auto.arima</code> con las series ajustadas sin outliers con <code>tso</code>:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb253-1" tabindex="-1"></a><span class="co"># Forecast ts Valledupar</span></span>
<span id="cb253-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb253-2" tabindex="-1"></a>VUP_temp_order <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(VUP_temp_outliers<span class="sc">$</span>yadj)</span>
<span id="cb253-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb253-3" tabindex="-1"></a>VUP_temp_tso <span class="ot">&lt;-</span> <span class="fu">forecast</span>(VUP_temp_order, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb253-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb253-4" tabindex="-1"></a>VUP_temp_tso</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 731       35.47045 33.60325 37.33766 32.61481 38.32609
## 732       35.40387 33.39455 37.41320 32.33087 38.47688
## 733       35.48766 33.36300 37.61232 32.23828 38.73704
## 734       35.49972 33.31234 37.68711 32.15440 38.84505
## 735       35.51322 33.27777 37.74867 32.09440 38.93204
## 736       35.51765 33.24397 37.79133 32.04036 38.99494
## 737       35.51996 33.21346 37.82647 31.99247 39.04746
## 738       35.52056 33.18504 37.85608 31.94868 39.09243
## 739       35.52045 33.15875 37.88216 31.90853 39.13238
## 740       35.51996 33.13438 37.90555 31.87153 39.16840
## 741       35.51930 33.11181 37.92679 31.83736 39.20124
## 742       35.51856 33.09089 37.94623 31.80576 39.23136
## 743       35.51779 33.07151 37.96408 31.77652 39.25907
## 744       35.51703 33.05353 37.98052 31.74943 39.28462
## 745       35.51627 33.03685 37.99569 31.72433 39.30822
## 746       35.51554 33.02138 38.00970 31.70105 39.33003
## 747       35.51483 33.00701 38.02265 31.67945 39.35021
## 748       35.51414 32.99366 38.03462 31.65939 39.36889
## 749       35.51347 32.98125 38.04570 31.64077 39.38618
## 750       35.51283 32.96971 38.05595 31.62346 39.40220
## 751       35.51221 32.95898 38.06544 31.60738 39.41704
## 752       35.51161 32.94899 38.07422 31.59243 39.43079
## 753       35.51103 32.93970 38.08236 31.57852 39.44354
## 754       35.51047 32.93105 38.08990 31.56558 39.45536
## 755       35.50993 32.92299 38.09688 31.55354 39.46632
## 756       35.50941 32.91547 38.10334 31.54233 39.47649
## 757       35.50891 32.90848 38.10934 31.53189 39.48592
## 758       35.50842 32.90195 38.11489 31.52217 39.49467
## 759       35.50795 32.89587 38.12004 31.51311 39.50279
## 760       35.50750 32.89019 38.12481 31.50467 39.51033</code></pre>
<p>Tal como en las <a href="modelos-estacionarios-en-series-de-tiempo.html#predicciones-arima">Predicciones ARIMA</a>, para Valledupar se obtienen predicciones ajustadas con tso muy cercanas (35.40 y 35.52 ºC, con variación de 0.12 ºC) y un valor promedio de 35.51 ºC.</p>
<p>Como se puede ver a continuación, para Medellín también se obtienen valores cercanos entre ellos (28.57 ºC - 28.84 ºC), con una variación de 0.27 ºC entre el mínimo y el máximo pronósticado. El promedio de las predicciones en este caso es de 28.76 ºC.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb255-1" tabindex="-1"></a><span class="co"># Forecast ts Medellín</span></span>
<span id="cb255-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb255-2" tabindex="-1"></a>MED_temp_order <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(MED_temp_outliers<span class="sc">$</span>yadj)</span>
<span id="cb255-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb255-3" tabindex="-1"></a>MED_temp_tso <span class="ot">&lt;-</span> <span class="fu">forecast</span>(MED_temp_order, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb255-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb255-4" tabindex="-1"></a>MED_temp_tso</span></code></pre></div>
<pre><code>##     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 731       28.64836 26.52477 30.77195 25.40062 31.89611
## 732       28.74427 26.47584 31.01271 25.27500 32.21354
## 733       28.56859 26.25180 30.88538 25.02537 32.11181
## 734       28.78553 26.44474 31.12633 25.20559 32.36547
## 735       28.61834 26.24962 30.98705 24.99570 32.24097
## 736       28.81121 26.42916 31.19325 25.16818 32.45423
## 737       28.65393 26.25444 31.05341 24.98423 32.32362
## 738       28.82656 26.41902 31.23409 25.14455 32.50856
## 739       28.67979 26.26050 31.09908 24.97980 32.37978
## 740       28.83512 26.41052 31.25971 25.12701 32.54322
## 741       28.69894 26.26581 31.13206 24.97780 32.42008
## 742       28.83925 26.40230 31.27620 25.11226 32.56624
## 743       28.71341 26.26986 31.15695 24.97633 32.45049
## 744       28.84054 26.39400 31.28708 25.09888 32.58220
## 745       28.72459 26.27266 31.17653 24.97468 32.47451
## 746       28.84004 26.38559 31.29450 25.08628 32.59381
## 747       28.73344 26.27436 31.19252 24.97260 32.49428
## 748       28.83846 26.37714 31.29978 25.07419 32.60273
## 749       28.74060 26.27517 31.20603 24.97005 32.51115
## 750       28.83625 26.36874 31.30376 25.06251 32.60999
## 751       28.74652 26.27526 31.21778 24.96705 32.52599
## 752       28.83372 26.36046 31.30697 25.05119 32.61624
## 753       28.75151 26.27476 31.22826 24.96364 32.53938
## 754       28.83105 26.35235 31.30976 25.04020 32.62190
## 755       28.75578 26.27377 31.23780 24.95988 32.55169
## 756       28.82839 26.34444 31.31233 25.02952 32.62725
## 757       28.75950 26.27239 31.24661 24.95579 32.56321
## 758       28.82579 26.33675 31.31483 25.01913 32.63245
## 759       28.76277 26.27067 31.25486 24.95143 32.57410
## 760       28.82331 26.32927 31.31735 25.00901 32.63762</code></pre>
<p>Y como se realizado con los modelos anteriores, se grafican las predicciones sin outliers / tso con <code>plot</code>:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb257-1" tabindex="-1"></a><span class="co"># Plot tso Valledupar</span></span>
<span id="cb257-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb257-2" tabindex="-1"></a><span class="fu">plot</span>(VUP_temp_tso, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>,</span>
<span id="cb257-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb257-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predicción TSO Temperatura máxima Valledupar&quot;</span>, </span>
<span id="cb257-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb257-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb257-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb257-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(VUP_temp_2018_2019), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb258-1" tabindex="-1"></a><span class="co"># Plot tso Medellín</span></span>
<span id="cb258-2"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb258-2" tabindex="-1"></a><span class="fu">plot</span>(MED_temp_tso, <span class="at">col =</span> <span class="st">&quot;lightgreen&quot;</span>, </span>
<span id="cb258-3"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb258-3" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predicción TSO Temperatura máxima Medellín&quot;</span>, </span>
<span id="cb258-4"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb258-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Tiempo / Día&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Temperatura [°C]&quot;</span>)</span>
<span id="cb258-5"><a href="modelos-estacionarios-en-series-de-tiempo.html#cb258-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(MED_temp_2022_2023), <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempo-RFCS_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
</div>
</div>
<div id="observaciones-predicciones" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Observaciones predicciones<a href="modelos-estacionarios-en-series-de-tiempo.html#observaciones-predicciones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este caso, las predicciones se realizaron sin problemas, pero los valores / forecasts encontrados por los modelos fueron los más “simple” que corresponden prácticamente a la media / promedio de cada serie:<br />
- Pronósticos de ~35.48, 35.45 y ~35.51 ºC en Valledupar contra la media de 35.48 ºC de la serie.<br />
- Pronósticos de ~28.79, 28.33 y ~28.76 ºC en Medellín contra la media de 27.93 ºC de la serie.<br />
Los anteriores resultados, nos llevarían a explorar otros métodos de pronóstico para la temperatura máxima diaria.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducción-modelos-pronóstico.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regresión-en-series-de-tiempo.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
